name: CI

on:
  workflow_call:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: install rust stable
        uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2

      - name: Install ALSA development libraries
        run: sudo apt-get update && sudo apt-get install -y libasound2-dev

      - run: cargo build --release
