name: CI

on:
  workflow_call:

jobs:
  release:
    runs-on: ubuntu-latest
    environment: release
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install ALSA development libraries
        run: sudo apt-get update && sudo apt-get install -y libasound2-dev

      - run: cargo publish --token ${{ secrets.CRATES_TOKEN }}
